### ISSUE TITLE
爬取手机超话，无法爬到

### ISSUE THREAD

**Issue by Bolero-web** [czy1999/weibo-topic-spider#27]
文件已存在
开始自动登陆，若出现验证码手动验证
暂停20秒，用于验证码验证
判断页面1成功 0失败  结果是=1
Traceback (most recent call last):
  File "D:/毕业论文/weibo-topic-spider-master/super-topic-spyder.py", line 268, in <module>
    spider(username,password,book_name_xls,sheet_name_xls,keyword,maxWeibo,num,save_pic)
  File "D:/毕业论文/weibo-topic-spider-master/super-topic-spyder.py", line 230, in spider
    elem = driver.find_element_by_xpath("//*[@class='m-text-cut']").click();
  File "C:\Users\21141\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\21141\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\21141\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\21141\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@class='m-text-cut']"}
  (Session info: chrome=87.0.4280.88)
  (Driver info: chromedriver=71.0.3578.137 (86ee722808adfe9e3c92e6e8ea746ade08423c7e),platform=Windows NT 10.0.18363 x86_64)
这是报错内容，看了其他issue也有出现这个错误，解释是说超话不存在，但是我这个手机超话是存在的呀，怎么会出现这种问题呢，求解

**Comment by czy1999** [comment]
超话名称是什么？

**Comment by Bolero-web** [comment]
> 超话名称是什么？

手机

**Comment by Tany99** [comment]
作者你好 有一个包 excelSave 是作者你自己写的嘛 ，pip install 找不到这个包
