### ISSUE TITLE
相关问题

### ISSUE THREAD

**Issue by xtll** [czy1999/weibo-topic-spider#3]
报错：
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="box-left m-box-col m-box-center-a">...</div> is not clickable at point (240, 643). Other element would receive the click: <div class="m-diy-btn m-box-col m-box-center m-box-center-a">...</div>
  (Session info: chrome=79.0.3945.130)
好像是窗口大小问题，不知道该如何解决

**Comment by czy1999** [comment]
我这边测试正常，请问报错的代码行数和爬取的话题是什么？

**Comment by xtll** [comment]
全部错误代码：
Traceback (most recent call last):
  File "D:/pycharm/weibo3.0/weibo-topic.py", line 198, in <module>
    spider(username, password, driver, book_name_xls, sheet_name_xls, keyword, maxWeibo)
  File "D:/pycharm/weibo3.0/weibo-topic.py", line 174, in spider
    elem.click()
  File "C:\Users\tkx\Anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\tkx\Anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\tkx\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\tkx\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="box-left m-box-col m-box-center-a">...</div> is not clickable at point (240, 643). Other element would receive the click: <div class="m-diy-btn m-box-col m-box-center m-box-center-a">...</div>
  (Session info: chrome=79.0.3945.130)
爬取话题为：江苏响水爆炸

**Comment by czy1999** [comment]
知道问题所在了，本项目是微博超级话题爬虫，而“江苏响水爆炸”不是微博超级话题，程序找不到超级话题框，所以报错了，我稍微修改了一下，你可以直接运行下面的代码爬取关于江苏响水爆炸的微博数据（将以下代码覆盖粘贴到weibo-topic-spyder.py，其他项目文件不变）



[weibo-topic-spyder.txt](https://github.com/czy1999/weibo-topic-spider/files/4142278/weibo-topic-spyder.txt)

**Comment by czy1999** [comment]
项目已更新，添加普通话题爬取代码
