### ISSUE TITLE
又爬不到内容了，求指教

### ISSUE THREAD

**Issue by wendy914** [czy1999/weibo-topic-spider#4]
我修改了一部分地方，但是还是出错了。您帮忙看看。
文件已存在
开始自动登陆，若出现验证码手动验证
暂停20秒，用于验证码验证
判断页面1成功 0失败  结果是=1
超话链接获取完毕，休眠2秒
Traceback (most recent call last):
  File "F:/宝洁商赛/微博爬虫/weibo.py", line 187, in <module>
    spider(username,password,driver,book_name_xls,sheet_name_xls,keyword,maxWeibo)
  File "F:/宝洁商赛/微博爬虫/weibo.py", line 167, in spider
    yuedu_taolun = driver.find_element_by_xpath("//*[@id='app']/div[1]/div[1]/div[1]/div[4]/div/div/div/a/div[2]/h4[1]").text
  File "D:\anaconda\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "D:\anaconda\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "D:\anaconda\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\anaconda\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='app']/div[1]/div[1]/div[1]/div[4]/div/div/div/a/div[2]/h4[1]"}
  (Session info: chrome=79.0.3945.130)

**Comment by czy1999** [comment]
请问爬取的话题是什么？

**Comment by wendy914** [comment]
> 请问爬取的话题是什么？

时代少年团

**Comment by czy1999** [comment]
是微博页面布局的问题，超话布局不同导致程序点击事件出错，将报错的这一句
`   elem = driver.find_element_by_xpath("//*[@class='box-left m-box-col m-box-center-a']")
`
引号部分修改为
`elem = driver.find_element_by_xpath("//*[@id='app']/div[1]/div[1]/div[3]/div/div/div[3]/div/div/div[1]")
`

**Comment by czy1999** [comment]
项目已更新，也可以重新拉取代码运行

**Comment by wendy914** [comment]
> 项目已更新，也可以重新拉取代码运行
谢谢！
