### ISSUE TITLE
爬取肺炎求助超话出了exception，请指教

### ISSUE THREAD

**Issue by Numenor-wilder** [czy1999/weibo-topic-spider#6]
报错如下：
DevTools listening on ws://127.0.0.1:5947/devtools/browser/311bbf3a-feea-4651-a9a7-137d6255c46e
文件已存在
开始自动登陆，若出现验证码手动验证
暂停20秒，用于验证码验证
判断页面1成功 0失败  结果是=1
Traceback (most recent call last):
  File "C:\Users\wangz\Source\Repos\weibo-topic-spider\weibo-topic-spyder.py", line 191, in <module>
    spider(username,password,driver,book_name_xls,sheet_name_xls,keyword,maxWeibo)
  File "C:\Users\wangz\Source\Repos\weibo-topic-spider\weibo-topic-spyder.py", line 168, in spider
    elem.click()
  File "C:\Users\wangz\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\wangz\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\wangz\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\wangz\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=80.0.3987.87)

我查了一下大概是说DOM上的元素改变导致报错，但是不知道如何修改，还望指教，感激不尽

**Comment by Numenor-wilder** [comment]
第二个elem.click()出错，都没有超话图标了当然点不了了😂

**Comment by czy1999** [comment]
已经修复，第二个click已经删去，感谢反馈
